openapi: 3.2.0
info:
  version: '2020-07-14'
  x-release: v4
  title: Amazon Interactive Video Service Get Stream API
  description: 'Introduction


    The Amazon Interactive Video Service (IVS) API is REST compatible, using a standard HTTP API and an Amazon Web Services EventBridge event stream for responses.'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: ivs
  x-aws-signingName: ivs
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/ivs-2020-07-14.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://ivs.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon IVS multi-region endpoint
- url: https://ivs.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon IVS multi-region endpoint
- url: http://ivs.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon IVS endpoint for China (Beijing) and China (Ningxia)
- url: https://ivs.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon IVS endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: GetStream
paths:
  /GetStream:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetStream
      description: Gets information about the active (live) stream on a specified channel.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetStreamResponse'
        '480':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '482':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '483':
          description: ChannelNotBroadcasting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelNotBroadcasting'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - channelArn
              properties:
                channelArn:
                  description: Channel ARN for stream to be accessed.
                  type: string
                  pattern: ^arn:aws:[is]vs:[a-z0-9-]+:[0-9]+:channel/[a-zA-Z0-9-]+$
                  minLength: 1
                  maxLength: 128
      summary: Amazon Interactive Video Service Get Stream
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - GetStream
components:
  schemas:
    PlaybackURL:
      type: string
    StreamViewerCount:
      type: integer
    ResourceNotFoundException: {}
    AccessDeniedException: {}
    ChannelNotBroadcasting: {}
    ValidationException: {}
    StreamState:
      type: string
      enum:
      - LIVE
      - OFFLINE
    ChannelArn:
      type: string
      pattern: ^arn:aws:[is]vs:[a-z0-9-]+:[0-9]+:channel/[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 128
    GetStreamResponse:
      type: object
      properties:
        stream:
          allOf:
          - $ref: '#/components/schemas/Stream'
          - description: <p/>
    StreamStartTime:
      type: string
      format: date-time
    StreamId:
      type: string
      pattern: ^st-[a-zA-Z0-9]+$
      minLength: 26
      maxLength: 26
    Stream:
      type: object
      properties:
        channelArn:
          allOf:
          - $ref: '#/components/schemas/ChannelArn'
          - description: Channel ARN for the stream.
        health:
          allOf:
          - $ref: '#/components/schemas/StreamHealth'
          - description: The stream’s health.
        playbackUrl:
          allOf:
          - $ref: '#/components/schemas/PlaybackURL'
          - description: URL of the master playlist, required by the video player to play the HLS stream.
        startTime:
          allOf:
          - $ref: '#/components/schemas/StreamStartTime'
          - description: Time of the stream’s start. This is an ISO 8601 timestamp; <i>note that this is returned as a string</i>.
        state:
          allOf:
          - $ref: '#/components/schemas/StreamState'
          - description: The stream’s state. Do not rely on the <code>OFFLINE</code> state, as the API may not return it; instead, a "NotBroadcasting" error will indicate that the stream is not live.
        streamId:
          allOf:
          - $ref: '#/components/schemas/StreamId'
          - description: Unique identifier for a live or previously live stream in the specified channel.
        viewerCount:
          allOf:
          - $ref: '#/components/schemas/StreamViewerCount'
          - description: A count of concurrent views of the stream. Typically, a new view appears in <code>viewerCount</code> within 15 seconds of when video playback starts and a view is removed from <code>viewerCount</code> within 1 minute of when video playback ends. A value of -1 indicates that the request timed out; in this case, retry.
      description: Specifies a live video stream that has been ingested and distributed.
    StreamHealth:
      type: string
      enum:
      - HEALTHY
      - STARVING
      - UNKNOWN
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/ivs/
x-hasEquivalentPaths: true
