openapi: 3.2.0
info:
  version: '2020-07-14'
  x-release: v4
  title: Amazon Interactive Video Service List Recording…
  description: 'Introduction


    The Amazon Interactive Video Service (IVS) API is REST compatible, using a standard HTTP API and an Amazon Web Services EventBridge event stream for responses.'
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: ivs
  x-aws-signingName: ivs
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/ivs-2020-07-14.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://ivs.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon IVS multi-region endpoint
- url: https://ivs.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon IVS multi-region endpoint
- url: http://ivs.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon IVS endpoint for China (Beijing) and China (Ningxia)
- url: https://ivs.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon IVS endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: ListRecordingConfigurations
paths:
  /ListRecordingConfigurations:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListRecordingConfigurations
      description: Gets summary information about all recording configurations in your account, in the Amazon Web Services region where the API request is processed.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListRecordingConfigurationsResponse'
        '480':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '482':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
      parameters:
      - name: maxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: nextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                maxResults:
                  description: 'Maximum number of recording configurations to return. Default: your service quota or 100, whichever is smaller. '
                  type: integer
                  minimum: 1
                  maximum: 100
                nextToken:
                  description: The first recording configuration to retrieve. This is used for pagination; see the <code>nextToken</code> response field.
                  type: string
                  pattern: ^[a-zA-Z0-9+/=_-]*$
                  minLength: 0
                  maxLength: 1024
      summary: Amazon Interactive Video Service List Recording Configurations
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - ListRecordingConfigurations
components:
  schemas:
    RecordingConfigurationArn:
      type: string
      pattern: ^arn:aws:ivs:[a-z0-9-]+:[0-9]+:recording-configuration/[a-zA-Z0-9-]+$
      minLength: 0
      maxLength: 128
    S3DestinationConfiguration:
      type: object
      required:
      - bucketName
      properties:
        bucketName:
          allOf:
          - $ref: '#/components/schemas/S3DestinationBucketName'
          - description: Location (S3 bucket name) where recorded videos will be stored.
      description: A complex type that describes an S3 location where recorded videos will be stored.
    RecordingConfigurationList:
      type: array
      items:
        $ref: '#/components/schemas/RecordingConfigurationSummary'
    RecordingConfigurationName:
      type: string
      pattern: ^[a-zA-Z0-9-_]*$
      minLength: 0
      maxLength: 128
    AccessDeniedException: {}
    ValidationException: {}
    ListRecordingConfigurationsResponse:
      type: object
      required:
      - recordingConfigurations
      properties:
        nextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: If there are more recording configurations than <code>maxResults</code>, use <code>nextToken</code> in the request to get the next set.
        recordingConfigurations:
          allOf:
          - $ref: '#/components/schemas/RecordingConfigurationList'
          - description: List of the matching recording configurations.
    PaginationToken:
      type: string
      pattern: ^[a-zA-Z0-9+/=_-]*$
      minLength: 0
      maxLength: 1024
    DestinationConfiguration:
      type: object
      properties:
        s3:
          allOf:
          - $ref: '#/components/schemas/S3DestinationConfiguration'
          - description: An S3 destination configuration where recorded videos will be stored.
      description: A complex type that describes a location where recorded videos will be stored. Each member represents a type of destination configuration. For recording, you define one and only one type of destination configuration.
    InternalServerException: {}
    S3DestinationBucketName:
      type: string
      pattern: ^[a-z0-9-.]+$
      minLength: 3
      maxLength: 63
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    RecordingConfigurationSummary:
      type: object
      required:
      - arn
      - destinationConfiguration
      - state
      properties:
        arn:
          allOf:
          - $ref: '#/components/schemas/RecordingConfigurationArn'
          - description: Recording-configuration ARN.
        destinationConfiguration:
          allOf:
          - $ref: '#/components/schemas/DestinationConfiguration'
          - description: A complex type that contains information about where recorded video will be stored.
        name:
          allOf:
          - $ref: '#/components/schemas/RecordingConfigurationName'
          - description: Recording-configuration name. The value does not need to be unique.
        state:
          allOf:
          - $ref: '#/components/schemas/RecordingConfigurationState'
          - description: Indicates the current state of the recording configuration. When the state is <code>ACTIVE</code>, the configuration is ready for recording a channel stream.
        tags:
          allOf:
          - $ref: '#/components/schemas/Tags'
          - description: Tags attached to the resource. Array of 1-50 maps, each of the form <code>string:string (key:value)</code>. See <a href="https://docs.aws.amazon.com/general/latest/gr/aws_tagging.html">Tagging Amazon Web Services Resources</a> for more information, including restrictions that apply to tags and "Tag naming limits and requirements"; Amazon IVS has no service-specific constraints beyond what is documented there.
      description: Summary information about a RecordingConfiguration.
    RecordingConfigurationState:
      type: string
      enum:
      - CREATING
      - CREATE_FAILED
      - ACTIVE
    Tags:
      type: object
      minProperties: 0
      maxProperties: 50
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
  parameters:
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/ivs/
x-hasEquivalentPaths: true
